<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace Authz;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>authz.CheckAnswer</code>
 */
class CheckAnswer extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string principal = 1;</code>
     */
    protected $principal = '';
    /**
     * Generated from protobuf field <code>string resource_kind = 2;</code>
     */
    protected $resource_kind = '';
    /**
     * Generated from protobuf field <code>string resource_value = 3;</code>
     */
    protected $resource_value = '';
    /**
     * Generated from protobuf field <code>string action = 4;</code>
     */
    protected $action = '';
    /**
     * Generated from protobuf field <code>bool is_allowed = 5;</code>
     */
    protected $is_allowed = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $principal
     *     @type string $resource_kind
     *     @type string $resource_value
     *     @type string $action
     *     @type bool $is_allowed
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Api::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string principal = 1;</code>
     * @return string
     */
    public function getPrincipal()
    {
        return $this->principal;
    }

    /**
     * Generated from protobuf field <code>string principal = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPrincipal($var)
    {
        GPBUtil::checkString($var, True);
        $this->principal = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string resource_kind = 2;</code>
     * @return string
     */
    public function getResourceKind()
    {
        return $this->resource_kind;
    }

    /**
     * Generated from protobuf field <code>string resource_kind = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setResourceKind($var)
    {
        GPBUtil::checkString($var, True);
        $this->resource_kind = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string resource_value = 3;</code>
     * @return string
     */
    public function getResourceValue()
    {
        return $this->resource_value;
    }

    /**
     * Generated from protobuf field <code>string resource_value = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setResourceValue($var)
    {
        GPBUtil::checkString($var, True);
        $this->resource_value = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string action = 4;</code>
     * @return string
     */
    public function getAction()
    {
        return $this->action;
    }

    /**
     * Generated from protobuf field <code>string action = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setAction($var)
    {
        GPBUtil::checkString($var, True);
        $this->action = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_allowed = 5;</code>
     * @return bool
     */
    public function getIsAllowed()
    {
        return $this->is_allowed;
    }

    /**
     * Generated from protobuf field <code>bool is_allowed = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsAllowed($var)
    {
        GPBUtil::checkBool($var);
        $this->is_allowed = $var;

        return $this;
    }

}

