<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace Authz;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>authz.PrincipalCreateResponse</code>
 */
class PrincipalCreateResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.authz.Principal principal = 1;</code>
     */
    protected $principal = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Authz\Principal $principal
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Api::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.authz.Principal principal = 1;</code>
     * @return \Authz\Principal|null
     */
    public function getPrincipal()
    {
        return $this->principal;
    }

    public function hasPrincipal()
    {
        return isset($this->principal);
    }

    public function clearPrincipal()
    {
        unset($this->principal);
    }

    /**
     * Generated from protobuf field <code>.authz.Principal principal = 1;</code>
     * @param \Authz\Principal $var
     * @return $this
     */
    public function setPrincipal($var)
    {
        GPBUtil::checkMessage($var, \Authz\Principal::class);
        $this->principal = $var;

        return $this;
    }

}

